name: CICD
on:
  push:
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2
      - name: Creating Env variable for Next Js
        touch ./frontend/.env.local
        echo NEXT_PUBLIC_FIREBASE_API_KEY =  ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} >> ./frontend/.env.local
        echo NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} >> ./frontend/.env.local
        echo NEXT_PUBLIC_FIREBASE_PROJECT_ID = ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} >> ./frontend/.env.local
        echo NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }} >> ./frontend/.env.local
        echo NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} >> ./frontend/.env.local
        echo NEXT_PUBLIC_FIREBASE_APP_ID = ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }} >> ./frontend/.env.local
        echo NEXT_PUBLIC_FIREBASE_DATABASE_URL = ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }} >> ./frontend/.env.local
        echo NEXT_PUBLIC_API_URL = ${{ secrets.NEXT_PUBLIC_API_URL }} >> ./frontend/.env.local

      - name: Build the docker-compose stack
        run: make run
      - name: Run Tests
        run: node puppeteer.js

        