name: Push-to-EC2
on:
  push:

jobs:
  build:
    name: CICD
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
      - name: Build the docker-compose stack
        run: make run
      - name: Run Tests
        run: node puppeteer.js
        <!-- env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} -->
        