name: CICD
on:
  push:
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: make run
      - name: Run Tests
        run: node puppeteer.js
        